import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from 'react'
import firebase from '../firebase'
import Layout from '../components/layout'
import {Card, Row, Col} from 'react-bootstrap'

export default function Home() {

  const [products, setProducts] = useState([])
  const [loading, setLoading] = useState(false)

  const ref = firebase.firestore().collection('products')

  function getProducts() {
    setLoading(true)
    ref.onSnapshot((querySnapshot) => {
      const items = []
      querySnapshot.forEach((doc) => {
        items.push(doc.data())
      });
      setProducts(items)
      setLoading(false)
    });
  }

  useEffect(()=>{
    getProducts()
  }, [])

  if(loading) {
    return <h1>Loading...</h1>
  }

  return (
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row>
        <h1 p={2}>Products</h1>
      </Row>
      <Row>
        {products.map((product) => (
          <Col md={3} key={product.id}>
            <Card className="mb-2">
              <Card.Body>
                <Card.Title>{product.name}</Card.Title>
                <Card.Text>{product.description}</Card.Text>
              </Card.Body>
            </Card>
          </Col>
        ))}
      </Row>
    </div>
    </Layout>
  )
}
