import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from 'react'
import firebase from '../firebase'

export default function Home() {

  const [products, setProducts] = useState([])
  const [loading, setLoading] = useState(false)

  const ref = firebase.firestore().collection('products')

  function getProducts() {
    setLoading(true)
    ref.onSnapshot((querySnapshot) => {
      const items = []
      querySnapshot.forEach((doc) => {
        items.push(doc.data())
      });
      setProducts(items)
      setLoading(false)
    });
  }

  useEffect(()=>{
    getProducts()
  }, [])

  if(loading) {
    return <h1>Loading...</h1>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Products</h1>
        {products.map((product) => (
          <div key={product.id}>
            <h2>{product.name}</h2>
            <p>{product.description}</p>
          </div>
        ))}
      </main>
    </div>
  )
}
