import Head from 'next/head'
//import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from 'react'
import firebase from '../firebase'
import Layout from '../components/layout'
import {Badge, Card, Row, Col} from 'react-bootstrap-v5'
import FilterBtn from '../components/filterbtn'

export default function Home() {

  const [products, setProducts] = useState([])
  const [loading, setLoading] = useState(false)
  const [topic, setTopic] = useState('south-china-sea')

  const ref = firebase.firestore().collection('products')

  const filterByTopic = (topic) => {
    setTopic(topic)
  }

  function getProducts() {
    setLoading(true)
    ref.where('topic','==',topic).onSnapshot((querySnapshot) => {
      const items = []
      querySnapshot.forEach((doc) => {
        items.push(doc.data())
      });
      setProducts(items)
      setLoading(false)
    });
  }

  useEffect(()=>{
    getProducts()
  }, [topic])

//  if(loading) {
//    return <h1>Loading...</h1>
//  }

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row>
        <p className="mb-2">Ano ang batayan mo sa iyong argumento? (<i>Char</i>) Ang site na ito ay ginawa "for the good of the society" kunuhay. Bitaw, wala na talaga akong maisip na website kung san pwede akong magkapera. Kaya <a href="/">Buy me a coffee</a> na. </p>
      </Row>
      <Row className="mb-2">
        <div arial-label="Filter by">
          <span>Filter: </span>
          <FilterBtn filterFunction={filterByTopic} topic='south-china-sea' active={topic=='south-china-sea'}>South China Sea</FilterBtn>
          <FilterBtn filterFunction={filterByTopic} topic='coa' active={topic=='coa'}>COA Audit</FilterBtn>
          <FilterBtn filterFunction={filterByTopic} topic='history' active={topic=='history'}>History</FilterBtn>
        </div>
      </Row>
      <Row>
        {products.map((product) => (
          <Col md={3} key={product.id}>
            <Card className="mb-2">
              <Card.Body>
                <Card.Title>{product.name}</Card.Title>
                <Card.Text>{product.description} </Card.Text>
              </Card.Body>
              {(product.topic)?
              <Card.Footer>
                <span className="badge bg-dark">{product?.topic}</span>
              </Card.Footer>
              : ' '}
            </Card>
          </Col>
        ))}
      </Row>
      <Row>
        {loading?<p>Loading...</p>:<></>}
      </Row>
    </Layout>
  )
}
